function  WWHBookData_Files(P)
{
P.fA("Online-Hilfe f\u00fcr Policy Management","FrontPage.htm");
P.fA("Einleitung","intro_help-1.htm");
P.fA("Was ist Policy Manager?","intro_help-2.htm");
P.fA("Policy Manager Befehlszeile und Browser-Schnittstellen im Vergleich","intro_help-3.htm");
P.fA("Zugriff auf die BMC Configuration Management-Dokumentation","intro_help-4.htm");
P.fA("Verwenden der Hilfe","intro_help-5.htm");
P.fA("Konfigurieren von Policy Manager","config-1.htm");
P.fA("Das Policy Management-Plugin","config-2.htm");
P.fA("Konfigurieren und Ver\u00f6ffentlichen des Policy Service-Plugin","config-3.htm");
P.fA("Plugin-Konfigurationsseite: Verzeichnisdienstfelder","config-4.htm");
P.fA("Einrichten von Zugriffskontrolllisten","config-5.htm");
P.fA("Verwenden der Zugriffskontrolle","config-6.htm");
P.fA("Konfigurieren der Policy Compliance-Einstellungen","config-7.htm");
P.fA("Anzeigen von Zielen und Packages","targ_pkg-01.htm");
P.fA("Zieltypen","targ_pkg-02.htm");
P.fA("Was ist das Ziel \"Alle Clients\"?","targ_pkg-03.htm");
P.fA("Was ist eine Collection?","targ_pkg-04.htm");
P.fA("Was ist ein ausgeschlossenes Ziel?","targ_pkg-05.htm");
P.fA("Was ist ein direkt zugewiesenes Ziel?","targ_pkg-06.htm");
P.fA("Anzeigen von Zielen","targ_pkg-07.htm");
P.fA("Anzeigen von Zielen","targ_pkg-08.htm");
P.fA("Anzeigen der Mitglieder eines Ziels","targ_pkg-09.htm");
P.fA("Suchen nach Zielen","targ_pkg-10.htm");
P.fA("Anzeigen von Zielinformationen","targ_pkg-11.htm");
P.fA("Anzeigen der einem Ziel zugewiesenen Packages","targ_pkg-12.htm");
P.fA("Was ist ein Package?","targ_pkg-13.htm");
P.fA("Anzeigen von Packages","targ_pkg-14.htm");
P.fA("Anzeigen von Packages","targ_pkg-15.htm");
P.fA("Suchen nach Packages","targ_pkg-16.htm");
P.fA("Anzeigen von Zielen, denen ein Package zugewiesen wurde","targ_pkg-17.htm");
P.fA("Anzeigen von Package-Informationen","targ_pkg-18.htm");
P.fA("Erstellen und Bearbeiten von Policys","policies-01.htm");
P.fA("Was ist eine Policy?","policies-02.htm");
P.fA("Task-Management","policies-03.htm");
P.fA("Allgemeine Anweisungen zum Erstellen und Bearbeiten von Policys","policies-04.htm");
P.fA("Erstellen der Vorschau und Speichern von Policy-\u00c4nderungen","policies-05.htm");
P.fA("Hinweise zum Speichern von Policys","policies-06.htm");
P.fA("Hinzuf\u00fcgen und Entfernen von Packages aus einer Policy","policies-07.htm");
P.fA("Hinzuf\u00fcgen von Packages zu einer Policy","policies-08.htm");
P.fA("Entfernen von Packages aus einer Policy","policies-09.htm");
P.fA("Festlegen von Status und Zeitpl\u00e4nen f\u00fcr Packages in einer Policy","policies-10.htm");
P.fA("\u00dcbersicht \u00fcber Installationsstatus","policies-11.htm");
P.fA("Angeben von Prim\u00e4r- und Sekund\u00e4rstatus","policies-12.htm");
P.fA("\u00dcberblick \u00fcber Package-Zeitpl\u00e4ne","policies-13.htm");
P.fA("Festlegen des Prim\u00e4r- und Sekund\u00e4rzeitplans f\u00fcr Packages","policies-14.htm");
P.fA("Festlegen des Aktualisierungszeitplans f\u00fcr Packages","policies-15.htm");
P.fA("Festlegen des Reparaturzeitplans f\u00fcr Packages","policies-16.htm");
P.fA("Festlegen allgemeiner Zeitpl\u00e4ne f\u00fcr mehrere Packages","policies-17.htm");
P.fA("Konfliktl\u00f6sung: Status und Zeitpl\u00e4ne in Policys","policies-18.htm");
P.fA("Aufl\u00f6sen von Unterschieden in Package-Status oder Package-Zeitpl\u00e4nen","policies-19.htm");
P.fA("Festlegen der Installationspriorit\u00e4t f\u00fcr Packages in einer Policy","policies-20.htm");
P.fA("Was ist die Installationspriorit\u00e4t?","policies-21.htm");
P.fA("Konfliktl\u00f6sung: Packages mit der gleichen Installationspriorit\u00e4t","policies-22.htm");
P.fA("Konfliktl\u00f6sung: mehrere Benutzer bearbeiten die gleiche Policy","policies-23.htm");
P.fA("Kopieren von Policys","policies-24.htm");
P.fA("L\u00f6schen von Policys","policies-25.htm");
P.fA("Verwalten von Software, Daten und Aktualisierungen","policies-26.htm");
P.fA("Anwendungsf\u00e4lle","policies-27.htm");
P.fA("Bearbeiten von Policys \u00fcber die Seite \"Package-Ansicht\"","policies-28.htm");
P.fA("Festlegen einer Blackout-Periode f\u00fcr ein Ziel","blackout-1.htm");
P.fA("Was ist eine Blackout-Periode?","blackout-2.htm");
P.fA("Festlegen der Blackout-Periode f\u00fcr ein Ziel","blackout-3.htm");
P.fA("Ausnehmen von Packages von der Blackout-Periode","blackout-4.htm");
P.fA("Angeben des Policy Service-Zeitplans f\u00fcr ein Ziel","sub_serv-1.htm");
P.fA("Was ist der Policy Service?","sub_serv-2.htm");
P.fA("Festlegen des Zeitplans f\u00fcr Policy Service-Aktualisierungen","sub_serv-3.htm");
P.fA("Einstellen der Tuner- und Package-Eigenschaften f\u00fcr ein Ziel","props-1.htm");
P.fA("\u00dcberblick \u00fcber Tuner- und Package-Policys","props-2.htm");
P.fA("Festlegen von Tuner-Eigenschaften","props-3.htm");
P.fA("Festlegen von Package-Eigenschaften","props-4.htm");
P.fA("Tuner- und Package-Eigenschaften, Format","props-5.htm");
P.fA("L\u00f6schen von Tuner- und Package-Eigenschaften","props-6.htm");
P.fA("Konfliktl\u00f6sung: Eigenschaftswerte","props-7.htm");
P.fA("Konfliktl\u00f6sung: Mehrere Benutzer bearbeiten Eigenschaften","props-8.htm");
P.fA("Festlegen von Transmitter-Berechtigungen f\u00fcr ein Ziel","tx_login-1.htm");
P.fA("Was sind Transmitter-Berechtigungen?","tx_login-2.htm");
P.fA("Hinzuf\u00fcgen und Bearbeiten von Transmitter-Berechtigungen","tx_login-3.htm");
P.fA("L\u00f6schen von Transmitter-Berechtigungen","tx_login-4.htm");
P.fA("Festlegen des Profils f\u00fcr ein Ziel","tx_login-5.htm");
P.fA("Was ist ein Profil?","tx_login-6.htm");
P.fA("\u00c4ndern des Profils f\u00fcr ein Ziel","tx_login-7.htm");
P.fA("Anzeigen der Policy Compliance","pol_comp-01.htm");
P.fA("Was ist Policy Compliance?","pol_comp-02.htm");
P.fA("Definition von Compliance","pol_comp-03.htm");
P.fA("Voraussetzungen f\u00fcr Policy Compliance","pol_comp-04.htm");
P.fA("Einrichten des Konsolenservers f\u00fcr Policy Compliance","pol_comp-05.htm");
P.fA("Einrichten von Clients f\u00fcr Policy Compliance","pol_comp-06.htm");
P.fA("Anzeigen der Policy Compliance f\u00fcr Ziele und Packages","pol_comp-07.htm");
P.fA("Gesamt-Compliance-Abfragen und Gesamt-Compliance-Berichte","pol_comp-08.htm");
P.fA("Compliance-Abfragen","pol_comp-09.htm");
P.fA("Compliance-Berichte","pol_comp-10.htm");
P.fA(" Integration mit Patch Management","patch-01.htm");
P.fA("Voraussetzungen f\u00fcr die Integration mit Patch Management","patch-02.htm");
P.fA("Was ist eine Patch-Gruppe?","patch-03.htm");
P.fA("Was ist ein Patch-Gruppe-Zuweisungsstatus?","patch-04.htm");
P.fA("Was ist Patch Service?","patch-05.htm");
P.fA("Zuweisen von Patch-Gruppen zu Zielen","patch-06.htm");
P.fA("Entfernen von Patch-Gruppen aus einer Policy","patch-07.htm");
P.fA("Simulation der Patch-Installation","patch-08.htm");
P.fA(" Anzeigen weiterer Informationen zur Installation von Patch-Gruppen","patch-09.htm");
P.fA("Konfigurieren der Neustarteinstellungen f\u00fcr Patch-Installationen","patch-10.htm");
P.fA("Erweitert: Tuner-Eigenschaften f\u00fcr die Neustarteinstellungen","patch-11.htm");
P.fA("Au\u00dferkraftsetzen des Patch Service-Aktualisierungszeitplans f\u00fcr Zielcomputer.","patch-12.htm");
P.fA("Ausnehmen von Patch Service von der Blackout-Periode.","patch-13.htm");
P.fA("Policy Compliance f\u00fcr  Patch-Gruppen","patch-14.htm");
P.fA("Sofortige Policy-Aktualisierungen: Integration mit Deployment Manager","update_now-1.htm");
P.fA("Voraussetzungen f\u00fcr die Integration mit Deployment Manager","update_now-2.htm");
P.fA("Aktivieren und Deaktivieren von sofortigen Policy-Aktualisierungen","update_now-3.htm");
P.fA("Durchf\u00fchren einer sofortigen Policy-Aktualisierung","update_now-4.htm");
P.fA("\u00dcberwachen und Anzeigen des Status einer Policy-Aktualisierung","update_now-5.htm");
P.fA("Anhalten und Wiederholen von Policy-Aktualisierungen","update_now-6.htm");
P.fA("Wie funktioniert die sofortige Policy-Aktualisierung?","update_now-7.htm");
P.fA("Blackout-Perioden und sofortige Policy-Aktualisierungen","update_now-8.htm");
P.fA("Prim\u00e4rzeitplan bearbeiten","z_schedule-1.htm");
P.fA("Sekund\u00e4rzeitplan bearbeiten","z_schedule-2.htm");
P.fA("Aktualisierungszeitplan bearbeiten","z_schedule-3.htm");
P.fA("Reparaturzeitplan bearbeiten","z_schedule-4.htm");
P.fA("Allgemeinen Zeitplan festlegen","z_schedule-5.htm");
P.fA("Package-Informationen","z_details-1.htm");
P.fA("Zielinformationen","z_details-2.htm");
P.fA("Zielansicht","z_targ_vw-1.htm");
P.fA("Aktualisierungsvorschau","z_targ_vw-2.htm");
P.fA("Status der Policy-Aktualisierung","z_targ_vw-3.htm");
P.fA("Blackout-Periode (Policy bearbeiten)","z_target_set-1.htm");
P.fA("Tuner- und Package-Eigenschaften (Policy bearbeiten &gt; Erweitert)","z_target_set-2.htm");
P.fA("Transmitter-Berechtigungen (Policy bearbeiten &gt; Erweitert)","z_target_set-3.htm");
P.fA("Transmitter-Berechtigungen hinzuf\u00fcgen/bearbeiten","z_target_set-4.htm");
P.fA("Installationspriorit\u00e4t","z_target_set-5.htm");
P.fA("Policy Service Zeitplan (Policy bearbeiten)","z_target_set-6.htm");
P.fA("Profil (Policy bearbeiten &gt; Erweitert)","z_target_set-7.htm");
P.fA("Profil ausw\u00e4hlen","z_target_set-8.htm");
P.fA("Package-Ansicht","z_pkg_vw-1.htm");
P.fA("Packages (Policy bearbeiten)","z_pol_asgn-1.htm");
P.fA("Vorschau der Policy-\u00c4nderungen","z_pol_asgn-2.htm");
P.fA("Vorschau l\u00f6schen","z_pol_asgn-3.htm");
P.fA("Policy kopieren","z_pol_asgn-4.htm");
P.fA("Zielliste bearbeiten","z_ar_targ-1.htm");
P.fA("Package-Liste bearbeiten","z_ar_pkg-1.htm");
P.fA("Package-List (vom Transmitter) bearbeiten","z_ar_pkg_tx-1.htm");
P.fA("Plugin-Konfiguration","z_pi_config-1.htm");
P.fA("Vorschau der Plugin-\u00c4nderungen","z_pi_config-2.htm");
P.fA("Konfiguration","z_config-1.htm");
P.fA("Erweiterte Optionen","z_config-2.htm");
P.fA("Compliance-Optionen","z_config-3.htm");
P.fA("Zugriffskontrolle","z_acl-1.htm");
P.fA("Zugriffskontrolle","z_acl-2.htm");
P.fA("Compliance: Zielansicht","z_pc-1.htm");
P.fA("Compliance: Package-Ansicht","z_pc-2.htm");
P.fA("Compliance-Berichte","z_pc-3.htm");
P.fA("Compliance-Informationen","z_pc-4.htm");
P.fA("Abfrage exportieren","z_pc-5.htm");
P.fA("Patch-Gruppen (Policy bearbeiten &gt; Patches)","z_patch-1.htm");
P.fA("Neustarteinstellungen (Policy bearbeiten &gt; Patches)","z_patch-2.htm");
P.fA("Patch Service-Zeitplan (Policy bearbeiten &gt; Patches)","z_patch-3.htm");
P.fA("Patch-Installation simulieren (Policy bearbeiten &gt; Patches)","z_patch-4.htm");
P.fA("Patch-Simulations-Logs (Policy bearbeiten &gt; Patches)","z_patch-5.htm");
P.fA("Vorschau der Policy-\u00c4nderungen","z_patch-6.htm");
P.fA("Patch-Gruppen-Liste bearbeiten (Policy bearbeiten &gt; Patches)","z_patch-7.htm");
}
