function  WWHBookData_Files(P)
{
P.fA("Ayuda en l\u00ednea de Policy Management","FrontPage.htm");
P.fA("Introducci\u00f3n","intro_help-1.htm");
P.fA("\u00bfQu\u00e9 es Policy Manager?","intro_help-2.htm");
P.fA("Policy Manager: la l\u00ednea de comandos frente a las interfaces de navegador  ","intro_help-3.htm");
P.fA("Acceder a la documentaci\u00f3n de BMC Configuration Management","intro_help-4.htm");
P.fA("Usar la ayuda","intro_help-5.htm");
P.fA("Configuraci\u00f3n de Policy Manager","config-1.htm");
P.fA("El complemento Policy Management ","config-2.htm");
P.fA("Configurar y publicar el complemento Policy Service ","config-3.htm");
P.fA("P\u00e1gina Configuraci\u00f3n de complemento: campos del servicio de directorios","config-4.htm");
P.fA("Configurar listas de control de acceso","config-5.htm");
P.fA("Usar la funci\u00f3n de control de acceso","config-6.htm");
P.fA("Configurar Policy Compliance ","config-7.htm");
P.fA("Vista de destinos y de paquetes","targ_pkg-01.htm");
P.fA("Tipos de destinos","targ_pkg-02.htm");
P.fA("\u00bfQu\u00e9 es el destino Todos los clientes finales?","targ_pkg-03.htm");
P.fA("\u00bfQu\u00e9 es una colecci\u00f3n?","targ_pkg-04.htm");
P.fA("\u00bfQu\u00e9 es un destino excluido?","targ_pkg-05.htm");
P.fA("\u00bfQu\u00e9 es un destino asignado directamente?","targ_pkg-06.htm");
P.fA("Visualizar destinos","targ_pkg-07.htm");
P.fA("Navegar por destinos","targ_pkg-08.htm");
P.fA("Visualizar los miembros de un destino","targ_pkg-09.htm");
P.fA("B\u00fascar destinos","targ_pkg-10.htm");
P.fA("Visualizar detalles de destino","targ_pkg-11.htm");
P.fA("Visualizar paquetes asignados a un destino","targ_pkg-12.htm");
P.fA("\u00bfQu\u00e9 es un paquete?","targ_pkg-13.htm");
P.fA("Vista de paquetes","targ_pkg-14.htm");
P.fA("Navegar por paquetes","targ_pkg-15.htm");
P.fA("B\u00fascar paquetes","targ_pkg-16.htm");
P.fA("Visualizar destinos asignados a un paquete","targ_pkg-17.htm");
P.fA("Visualizar detalles de paquete","targ_pkg-18.htm");
P.fA("Crear y editar pol\u00edticas","policies-01.htm");
P.fA("\u00bfQu\u00e9 es una pol\u00edtica?","policies-02.htm");
P.fA("Gesti\u00f3n de tareas","policies-03.htm");
P.fA("Instrucciones generales para la creaci\u00f3n y edici\u00f3n de pol\u00edticas","policies-04.htm");
P.fA("Visualizar previamente y almacenar cambios en las pol\u00edticas","policies-05.htm");
P.fA("Notas sobre el almacenamiento de pol\u00edticas","policies-06.htm");
P.fA("Agregar y eliminar paquetes de una pol\u00edtica","policies-07.htm");
P.fA("Adici\u00f3n de paquetes a una pol\u00edtica","policies-08.htm");
P.fA("Eliminar paquetes de una pol\u00edtica","policies-09.htm");
P.fA("Especificar estados y planificaciones de paquetes de una pol\u00edtica","policies-10.htm");
P.fA("Descripci\u00f3n general de estados de instalaci\u00f3n","policies-11.htm");
P.fA("Especificar estados principal y secundario","policies-12.htm");
P.fA("Descripci\u00f3n general de planificaciones de paquetes","policies-13.htm");
P.fA("Configurar la planificaci\u00f3n principal y secundaria de los paquetes","policies-14.htm");
P.fA("Configurar la planificaci\u00f3n de actualizaci\u00f3n de los paquetes","policies-15.htm");
P.fA("Configurar la planificaci\u00f3n de reparaci\u00f3n de los paquetes","policies-16.htm");
P.fA("Configurar planificaciones comunes para varios paquetes","policies-17.htm");
P.fA("Resoluci\u00f3n de conflictos: estados y planificaciones de pol\u00edticas","policies-18.htm");
P.fA("Resolver diferencias en los estados o las planificaciones de los paquetes","policies-19.htm");
P.fA("Configurar la prioridad de instalaci\u00f3n de los paquetes de una pol\u00edtica","policies-20.htm");
P.fA("\u00bfQu\u00e9 es una prioridad de instalaci\u00f3n?","policies-21.htm");
P.fA("Resoluci\u00f3n de conflictos: paquetes con la misma prioridad de instalaci\u00f3n","policies-22.htm");
P.fA("Resoluci\u00f3n de conflictos: cuando varios usuarios editan la misma pol\u00edtica ","policies-23.htm");
P.fA("Copiar pol\u00edticas","policies-24.htm");
P.fA("Eliminar pol\u00edticas","policies-25.htm");
P.fA("Administraci\u00f3n del software, datos y actualizaciones","policies-26.htm");
P.fA("Posibles situaciones","policies-27.htm");
P.fA("Editar pol\u00edticas en Vista de paquete","policies-28.htm");
P.fA("Establecer un periodo de exclusi\u00f3n para un destino","blackout-1.htm");
P.fA("\u00bfQu\u00e9 es un periodo de exclusi\u00f3n?","blackout-2.htm");
P.fA("Establecer el periodo de exclusi\u00f3n para un destino","blackout-3.htm");
P.fA("Exenci\u00f3n de los paquetes del periodo de exclusi\u00f3n","blackout-4.htm");
P.fA("Especificar la planificaci\u00f3n de Policy Service para un destino","sub_serv-1.htm");
P.fA("\u00bfQu\u00e9 es Policy Service?","sub_serv-2.htm");
P.fA("Configurar la planificaci\u00f3n para llevar a cabo las actualizaciones de Policy Service ","sub_serv-3.htm");
P.fA("Definir propiedades de tuner y paquete para un destino","props-1.htm");
P.fA("Aspectos generales de las pol\u00edticas de tuner y paquete","props-2.htm");
P.fA("Definir propiedades de tuner","props-3.htm");
P.fA("Definir propiedades de paquete","props-4.htm");
P.fA("Formato de propiedades de tuner y de paquete","props-5.htm");
P.fA("Eliminar propiedades de tuner y de paquete","props-6.htm");
P.fA("Resoluci\u00f3n de conflictos: valores de propiedad","props-7.htm");
P.fA("Resoluci\u00f3n de conflictos: cuando varios usuarios editan propiedades","props-8.htm");
P.fA("Especificar permisos de transmitter para un destino","tx_login-1.htm");
P.fA("\u00bfQu\u00e9 son los permisos de transmitter?","tx_login-2.htm");
P.fA("Agregar o editar permisos de transmitter","tx_login-3.htm");
P.fA("Eliminar permisos de transmitter","tx_login-4.htm");
P.fA("Especificar el perfil de un destino","tx_login-5.htm");
P.fA("\u00bfQu\u00e9 es un perfil?","tx_login-6.htm");
P.fA("Cambiar el perfil para un destino","tx_login-7.htm");
P.fA("Visualizar cumplimiento de pol\u00edticas","pol_comp-01.htm");
P.fA("\u00bfQu\u00e9 es Policy Compliance?","pol_comp-02.htm");
P.fA("Definici\u00f3n de cumplimiento","pol_comp-03.htm");
P.fA("Requisitos previos de Policy Compliance","pol_comp-04.htm");
P.fA("Configurar el servidor de consola para Policy Compliance","pol_comp-05.htm");
P.fA("Configurar clientes finales para Policy Compliance","pol_comp-06.htm");
P.fA("Visualizar cumplimiento de pol\u00edticas de paquetes y destinos","pol_comp-07.htm");
P.fA("Consultas e informes de cumplimiento general","pol_comp-08.htm");
P.fA("Consultas de cumplimiento","pol_comp-09.htm");
P.fA("Informes de cumplimiento","pol_comp-10.htm");
P.fA("Integraci\u00f3n con Patch Management","patch-01.htm");
P.fA("Requisitos previos para la integraci\u00f3n con Patch Management","patch-02.htm");
P.fA("\u00bfQu\u00e9 es un grupo de parches?","patch-03.htm");
P.fA("\u00bfQu\u00e9 es un estado de asignaci\u00f3n de un grupo de parches?","patch-04.htm");
P.fA("\u00bfQu\u00e9 es Patch Service?","patch-05.htm");
P.fA("Asignar grupos de parches a destinos","patch-06.htm");
P.fA("Eliminar grupos de parches de una pol\u00edtica","patch-07.htm");
P.fA("Simular la instalaci\u00f3n de parches","patch-08.htm");
P.fA("Visualizar de informaci\u00f3n adicional sobre la instalaci\u00f3n de grupos de parches","patch-09.htm");
P.fA("Configurar par\u00e1metros de reinicio de instalaciones de parches","patch-10.htm");
P.fA("Avanzadas: propiedades de configuraci\u00f3n de reinicio de Tuner","patch-11.htm");
P.fA("Sustituir la planificaci\u00f3n de actualizaci\u00f3n de Patch Service de las m\u00e1quinas de destino","patch-12.htm");
P.fA("Exenci\u00f3n de Patch Service del periodo de exclusi\u00f3n","patch-13.htm");
P.fA("Cumplimiento de pol\u00edticas de los grupos de parches","patch-14.htm");
P.fA("Actualizaciones inmediatas de pol\u00edticas: integraci\u00f3n con Deployment Manager","update_now-1.htm");
P.fA("Prerrequisitos para la integraci\u00f3n con Deployment Manager","update_now-2.htm");
P.fA("Habilitar y deshabilitar actualizaciones inmediatas de pol\u00edtica","update_now-3.htm");
P.fA("Realizar una actualizaci\u00f3n inmediata de pol\u00edtica","update_now-4.htm");
P.fA("Supervisar y visualizar del estado de una actualizaci\u00f3n de pol\u00edtica","update_now-5.htm");
P.fA("Detener y reiniciar las actualizaciones de pol\u00edticas","update_now-6.htm");
P.fA("\u00bfC\u00f3mo funciona la actualizaci\u00f3n inmediata de una pol\u00edtica?","update_now-7.htm");
P.fA("Periodos de exclusi\u00f3n y actualizaciones inmediatas de pol\u00edticas","update_now-8.htm");
P.fA("Editar la planificaci\u00f3n principal","z_schedule-1.htm");
P.fA("Editar la planificaci\u00f3n secundaria","z_schedule-2.htm");
P.fA("Editar la planificaci\u00f3n de actualizaci\u00f3n","z_schedule-3.htm");
P.fA("Edici\u00f3n de planificaci\u00f3n de reparaci\u00f3n","z_schedule-4.htm");
P.fA("Establecer planificaci\u00f3n com\u00fan","z_schedule-5.htm");
P.fA("Detalles del paquete","z_details-1.htm");
P.fA("Detalles de destino","z_details-2.htm");
P.fA("Vista de destino","z_targ_vw-1.htm");
P.fA("Actualizar vista previa","z_targ_vw-2.htm");
P.fA("Estado de actualizaci\u00f3n de pol\u00edtica","z_targ_vw-3.htm");
P.fA("Per\u00edodo de exclusi\u00f3n (Editar directiva)","z_target_set-1.htm");
P.fA("Propiedades del tuner y del paquete (Editar\u00a0directiva &gt; Opciones avanzadas)","z_target_set-2.htm");
P.fA("Permisos de transmitter (Editar directiva &gt; Opciones avanzadas)","z_target_set-3.htm");
P.fA("Agregar/editar permisos de transmitter","z_target_set-4.htm");
P.fA("Prioridad de instalaci\u00f3n","z_target_set-5.htm");
P.fA("Policy Service Planificar (Editar directiva)","z_target_set-6.htm");
P.fA("Perfil (Editar directiva &gt; Opciones avanzadas)","z_target_set-7.htm");
P.fA("Seleccionar perfil","z_target_set-8.htm");
P.fA("Vista de paquete","z_pkg_vw-1.htm");
P.fA("Paquetes (Editar directiva)","z_pol_asgn-1.htm");
P.fA("Obtener vista previa de los cambios en la directiva","z_pol_asgn-2.htm");
P.fA("Eliminar vista previa","z_pol_asgn-3.htm");
P.fA("Copiar pol\u00edtica","z_pol_asgn-4.htm");
P.fA("Editar lista de destinos","z_ar_targ-1.htm");
P.fA("Editar lista de paquetes","z_ar_pkg-1.htm");
P.fA("Editar lista de paquetes (de Transmitter)","z_ar_pkg_tx-1.htm");
P.fA("Configuraci\u00f3n de complemento","z_pi_config-1.htm");
P.fA("Vista previa de los cambios del complemento","z_pi_config-2.htm");
P.fA("Configuraci\u00f3n","z_config-1.htm");
P.fA("Opciones avanzadas","z_config-2.htm");
P.fA("Opciones de cumplimiento","z_config-3.htm");
P.fA("Control de acceso","z_acl-1.htm");
P.fA("Control de acceso","z_acl-2.htm");
P.fA("Cumplimiento: Vista de destino","z_pc-1.htm");
P.fA("Cumplimiento: vista de paquete","z_pc-2.htm");
P.fA("Informes de cumplimiento","z_pc-3.htm");
P.fA("Detalles de cumplimiento","z_pc-4.htm");
P.fA("Exportar consulta","z_pc-5.htm");
P.fA("Patch Groups (Editar directiva &gt; Parches)","z_patch-1.htm");
P.fA("Configuraci\u00f3n de reinicio (Editar directiva &gt; Parches)","z_patch-2.htm");
P.fA("Planificar Patch Service (Editar directiva &gt; Parches)","z_patch-3.htm");
P.fA("Simular la instalaci\u00f3n de un parche (Editar directiva &gt; Parches)","z_patch-4.htm");
P.fA("Logs de simulaci\u00f3n de parches (Editar directiva &gt; Parches)","z_patch-5.htm");
P.fA("Obtener vista previa de los cambios en la directiva","z_patch-6.htm");
P.fA("Editar lista de Patch Group (Editar directiva &gt; Parches)","z_patch-7.htm");
}
