function  WWHBookData_Files(P)
{
P.fA("Aide en ligne de Policy Management","FrontPage.htm");
P.fA("Introduction","intro_help-1.htm");
P.fA("D\u00e9finition de Policy Manager","intro_help-2.htm");
P.fA("Interfaces de navigateur et lignes de commande de Policy Manager","intro_help-3.htm");
P.fA("Acc\u00e8s \u00e0 la documentation relative \u00e0 BMC Configuration Management","intro_help-4.htm");
P.fA("Utilisation de l'aide","intro_help-5.htm");
P.fA("Configuration de Policy Manager","config-1.htm");
P.fA("Plugin Policy Management","config-2.htm");
P.fA("Configuration et publication du plugin Policy Service","config-3.htm");
P.fA("Page de configuration du plugin\u00a0: champs du service d'annuaire","config-4.htm");
P.fA("Configuration des listes de contr\u00f4le d'acc\u00e8s","config-5.htm");
P.fA("Utilisation de la fonction de contr\u00f4le d'acc\u00e8s","config-6.htm");
P.fA("Configuration des param\u00e8tres de la fonction policy compliance","config-7.htm");
P.fA("Affichage des cibles et des packages","targ_pkg-01.htm");
P.fA("Types de cibles","targ_pkg-02.htm");
P.fA("D\u00e9finition de la cible Toutes les machines cibles","targ_pkg-03.htm");
P.fA("D\u00e9finition d'une collection","targ_pkg-04.htm");
P.fA("D\u00e9finition d'une cible exclue","targ_pkg-05.htm");
P.fA("D\u00e9finition d'une cible en attribution directe","targ_pkg-06.htm");
P.fA("Affichage des cibles","targ_pkg-07.htm");
P.fA("Exploration des cibles","targ_pkg-08.htm");
P.fA("Affichage des membres d'une cible","targ_pkg-09.htm");
P.fA("Recherche de cibles","targ_pkg-10.htm");
P.fA("Affichage des d\u00e9tails de la cible","targ_pkg-11.htm");
P.fA("Affichage des packages attribu\u00e9s \u00e0 une cible","targ_pkg-12.htm");
P.fA("D\u00e9finition d'un package","targ_pkg-13.htm");
P.fA("Affichage des packages","targ_pkg-14.htm");
P.fA("Exploration des packages","targ_pkg-15.htm");
P.fA("Recherche de packages","targ_pkg-16.htm");
P.fA("Affichage des cibles auxquelles un package a \u00e9t\u00e9 attribu\u00e9","targ_pkg-17.htm");
P.fA("Affichage des d\u00e9tails du package","targ_pkg-18.htm");
P.fA("Cr\u00e9ation et modification des policies","policies-01.htm");
P.fA("D\u00e9finition d'une policy","policies-02.htm");
P.fA("Gestion de t\u00e2ches","policies-03.htm");
P.fA("Instructions g\u00e9n\u00e9rales pour la cr\u00e9ation et la modification de policies","policies-04.htm");
P.fA("Aper\u00e7u et enregistrement des modifications de policy","policies-05.htm");
P.fA("Remarques sur l'enregistrement des policies","policies-06.htm");
P.fA("Ajout et suppression des packages d'une policy","policies-07.htm");
P.fA("Ajout de packages \u00e0 une policy","policies-08.htm");
P.fA("Suppression de packages d'une policy","policies-09.htm");
P.fA("Indication des \u00e9tats et des planifications pour les packages d'une policy","policies-10.htm");
P.fA("Pr\u00e9sentation des \u00e9tats d'installation","policies-11.htm");
P.fA("Indication des \u00e9tats primaires et secondaires","policies-12.htm");
P.fA("Pr\u00e9sentation des planifications de package","policies-13.htm");
P.fA("D\u00e9finition de la planification primaire et secondaire pour les packages","policies-14.htm");
P.fA("D\u00e9finition de la planification de mise \u00e0 jour pour les packages","policies-15.htm");
P.fA("D\u00e9finition de la planification de r\u00e9paration pour les packages","policies-16.htm");
P.fA("D\u00e9finition des planifications communes \u00e0 plusieurs packages","policies-17.htm");
P.fA("R\u00e9solution de conflit\u00a0: \u00e9tats et planifications dans les policies","policies-18.htm");
P.fA("R\u00e9solution des diff\u00e9rences d'\u00e9tats ou de planifications des packages","policies-19.htm");
P.fA("D\u00e9finition de la priorit\u00e9 d'installation pour les packages dans une policy","policies-20.htm");
P.fA("D\u00e9finition de la priorit\u00e9 d'installation","policies-21.htm");
P.fA("R\u00e9solution de conflit\u00a0: packages avec la m\u00eame priorit\u00e9 d'installation","policies-22.htm");
P.fA("R\u00e9solution de conflit\u00a0: plusieurs utilisateurs modifiant la m\u00eame policy","policies-23.htm");
P.fA("Copie de policies","policies-24.htm");
P.fA("Suppression de policies","policies-25.htm");
P.fA("Gestion du logiciel, des donn\u00e9es et des mises \u00e0 jour","policies-26.htm");
P.fA("Cas d'emploi","policies-27.htm");
P.fA("Modification des policies \u00e0 partir de la Vue Package","policies-28.htm");
P.fA("D\u00e9finition de la p\u00e9riode d\u2019inactivit\u00e9 d\u2019une cible","blackout-1.htm");
P.fA("P\u00e9riode d'inactivit\u00e9 - D\u00e9finition","blackout-2.htm");
P.fA("D\u00e9finition de la p\u00e9riode d\u2019inactivit\u00e9 d\u2019une cible","blackout-3.htm");
P.fA("Exemption des packages de la p\u00e9riode d'inactivit\u00e9","blackout-4.htm");
P.fA("D\u00e9finition de la planification de Policy Service pour une cible","sub_serv-1.htm");
P.fA("D\u00e9finition de Policy Service","sub_serv-2.htm");
P.fA("Param\u00e9trage de la planification des mises \u00e0 jour de Policy Service","sub_serv-3.htm");
P.fA("Param\u00e9trage des propri\u00e9t\u00e9s de tuner et de package d'une cible","props-1.htm");
P.fA("Pr\u00e9sentation des policies de tuner et de package","props-2.htm");
P.fA("Param\u00e9trage des propri\u00e9t\u00e9s de tuner","props-3.htm");
P.fA("Param\u00e9trage des propri\u00e9t\u00e9s de package","props-4.htm");
P.fA("Format des propri\u00e9t\u00e9s de tuner et de package","props-5.htm");
P.fA("Suppression de propri\u00e9t\u00e9s de tuner et de package","props-6.htm");
P.fA("R\u00e9solution de conflit\u00a0: propri\u00e9t\u00e9s, valeurs","props-7.htm");
P.fA("R\u00e9solution de conflit\u00a0: modification de propri\u00e9t\u00e9s par plusieurs utilisateurs","props-8.htm");
P.fA("D\u00e9finition des droits du transmitter pour une cible","tx_login-1.htm");
P.fA("D\u00e9finition des droits du transmitter","tx_login-2.htm");
P.fA("Ajout ou modification des droits du transmitter","tx_login-3.htm");
P.fA("Suppression de droits du transmitter","tx_login-4.htm");
P.fA("D\u00e9finition du profil pour une cible","tx_login-5.htm");
P.fA("D\u00e9finition d'un profil","tx_login-6.htm");
P.fA("Modification du profil pour une cible","tx_login-7.htm");
P.fA("Affichage de la policy compliance","pol_comp-01.htm");
P.fA("D\u00e9finition de la policy compliance","pol_comp-02.htm");
P.fA("D\u00e9finition de la conformit\u00e9","pol_comp-03.htm");
P.fA("Pr\u00e9-requis \u00e0 la policy compliance","pol_comp-04.htm");
P.fA("Configuration du serveur console pour la policy compliance","pol_comp-05.htm");
P.fA("Configuration des machines cibles pour la policy compliance","pol_comp-06.htm");
P.fA("Affichage de la policy compliance pour les cibles et packages","pol_comp-07.htm");
P.fA("Requ\u00eates de conformit\u00e9 g\u00e9n\u00e9rale et rapports de conformit\u00e9","pol_comp-08.htm");
P.fA("Requ\u00eates de conformit\u00e9","pol_comp-09.htm");
P.fA("Rapports de conformit\u00e9","pol_comp-10.htm");
P.fA("Int\u00e9gration \u00e0 Patch Management","patch-01.htm");
P.fA("Pr\u00e9-requis \u00e0 l'int\u00e9gration \u00e0 Patch Management","patch-02.htm");
P.fA("D\u00e9finition d'un groupe de patchs","patch-03.htm");
P.fA("D\u00e9finition d'un \u00e9tat d'attribution de groupe de patch","patch-04.htm");
P.fA("D\u00e9finition de Patch Service","patch-05.htm");
P.fA("Attribution de groupes de patch aux cibles","patch-06.htm");
P.fA("Suppression de groupes de patch d'une policy","patch-07.htm");
P.fA("Simulation de l'installation de patchs","patch-08.htm");
P.fA("Affichage des informations d\u00e9taill\u00e9es sur l'installation de groupes de patch","patch-09.htm");
P.fA("Configuration des param\u00e8tres de red\u00e9marrage pour les installations de patchs","patch-10.htm");
P.fA("Avanc\u00e9 : propri\u00e9t\u00e9s de tuner pour les param\u00e8tres de red\u00e9marrage","patch-11.htm");
P.fA("Remplacement de la planification des mises \u00e0 jour de Patch Service pour les machines cibles","patch-12.htm");
P.fA("Exemption de Patch Service de la p\u00e9riode d'inactivit\u00e9","patch-13.htm");
P.fA("Policy compliance pour les groupes de patch","patch-14.htm");
P.fA("Mises \u00e0 jour imm\u00e9diates de la policy\u00a0: Int\u00e9gration \u00e0 Deployment Manager","update_now-1.htm");
P.fA("Pr\u00e9-requis de l'int\u00e9gration \u00e0 Deployment Management","update_now-2.htm");
P.fA("Activation et d\u00e9sactivation des mises \u00e0 jour imm\u00e9diates de la policy","update_now-3.htm");
P.fA("Ex\u00e9cution d'une mise \u00e0 jour imm\u00e9diate de la policy","update_now-4.htm");
P.fA("Contr\u00f4le et affichage du statut d'une mise \u00e0 jour de la policy","update_now-5.htm");
P.fA("Arr\u00eat et nouvelle tentative de mise \u00e0 jour de la policy","update_now-6.htm");
P.fA("Comment fonctionne la mise \u00e0 jour imm\u00e9diate de la policy\u00a0?","update_now-7.htm");
P.fA("P\u00e9riodes d'inactivit\u00e9 et mises \u00e0 jour imm\u00e9diates de la policy","update_now-8.htm");
P.fA("Modification de la planification primaire","z_schedule-1.htm");
P.fA("Modification de la planification secondaire","z_schedule-2.htm");
P.fA("Modification de la planification des mises \u00e0 jour","z_schedule-3.htm");
P.fA("Modification de la planification des r\u00e9parations","z_schedule-4.htm");
P.fA("D\u00e9finition d'une planification commune","z_schedule-5.htm");
P.fA("D\u00e9tails d'un package","z_details-1.htm");
P.fA("D\u00e9tails d'une cible","z_details-2.htm");
P.fA("Vue Cible","z_targ_vw-1.htm");
P.fA("Mise \u00e0 jour de l'aper\u00e7u","z_targ_vw-2.htm");
P.fA("Statut de la mise \u00e0 jour de la policy","z_targ_vw-3.htm");
P.fA("P\u00e9riode d'inactivit\u00e9 (Modifier Policy)","z_target_set-1.htm");
P.fA("Propri\u00e9t\u00e9s du tuner et du package (Modifier Policy &gt; Avanc\u00e9)","z_target_set-2.htm");
P.fA("Droits du transmitter (Modifier Policy &gt; Avanc\u00e9)","z_target_set-3.htm");
P.fA("Ajout/Modification des droits du transmitter","z_target_set-4.htm");
P.fA("Priorit\u00e9 d'installation","z_target_set-5.htm");
P.fA("Planification de Policy Service (Modification de policy)","z_target_set-6.htm");
P.fA("Profil (Modifier Policy &gt; Avanc\u00e9)","z_target_set-7.htm");
P.fA("S\u00e9lection d'un profil","z_target_set-8.htm");
P.fA("Vue Package","z_pkg_vw-1.htm");
P.fA("Packages (Modifier Policy)","z_pol_asgn-1.htm");
P.fA("V\u00e9rification de la modification d'une policy","z_pol_asgn-2.htm");
P.fA("Suppression de l'aper\u00e7u","z_pol_asgn-3.htm");
P.fA("Copie d'une policy","z_pol_asgn-4.htm");
P.fA("Modification de la liste de cibles","z_ar_targ-1.htm");
P.fA("Modification de la liste de packages","z_ar_pkg-1.htm");
P.fA("Modification de la liste de packages (\u00e0 partir du transmitter)","z_ar_pkg_tx-1.htm");
P.fA("Configuration du plugin","z_pi_config-1.htm");
P.fA("Aper\u00e7u des modifications du plugin","z_pi_config-2.htm");
P.fA("Configuration","z_config-1.htm");
P.fA("Options avanc\u00e9es","z_config-2.htm");
P.fA("Options de conformit\u00e9","z_config-3.htm");
P.fA("Contr\u00f4le d'acc\u00e8s","z_acl-1.htm");
P.fA("Contr\u00f4le d'acc\u00e8s","z_acl-2.htm");
P.fA("Conformit\u00e9\u00a0: Vue Cible","z_pc-1.htm");
P.fA("Conformit\u00e9\u00a0: Vue Package","z_pc-2.htm");
P.fA("Rapports de conformit\u00e9","z_pc-3.htm");
P.fA("D\u00e9tails de conformit\u00e9","z_pc-4.htm");
P.fA("Requ\u00eate d'exportation","z_pc-5.htm");
P.fA("Groupes de patchs (Modifier Policy &gt; Patchs)","z_patch-1.htm");
P.fA("Param\u00e8tres de red\u00e9marrage (Modifier Policy &gt; Patchs)","z_patch-2.htm");
P.fA("Planification de Patch Service (Modifier Policy &gt; Patchs)","z_patch-3.htm");
P.fA("Simulation de l'installation de patchs (Modifier policy &gt; Patchs)","z_patch-4.htm");
P.fA("Logs de simulation de patchs (Modifier Policy &gt; Patchs)","z_patch-5.htm");
P.fA("V\u00e9rification de la modification d'une policy","z_patch-6.htm");
P.fA("Modification de la liste de groupes de patchs (Modifier Policy &gt; Patchs)","z_patch-7.htm");
}
