function  WWHBookData_Files(P)
{
P.fA("Online help for Policy Management","FrontPage.htm");
P.fA("Introduction","intro_help-1.htm");
P.fA("What is Policy Manager?","intro_help-2.htm");
P.fA("Policy Manager command-line vs. browser interfaces","intro_help-3.htm");
P.fA("Accessing BMC CM documentation","intro_help-4.htm");
P.fA("Using the CM Documentation channel","intro_help-5.htm");
P.fA("Using the BMC Customer Support website","intro_help-6.htm");
P.fA("Using help","intro_help-7.htm");
P.fA("Configuring Policy Manager","config-1.htm");
P.fA("The Policy Management plug-in","config-2.htm");
P.fA("Configuring and publishing the Policy Service plug-in","config-3.htm");
P.fA("Starting or stopping the plug-in ","config-4.htm");
P.fA("Plug-in configuration page: directory service fields","config-5.htm");
P.fA("Setting up access control lists","config-6.htm");
P.fA("Using the access control feature","config-7.htm");
P.fA("Configuring policy compliance settings","config-8.htm");
P.fA("Creating and managing profiles for Windows Power Options","config-9.htm");
P.fA("Viewing targets and packages","targ_pkg-01.htm");
P.fA("Types of targets","targ_pkg-02.htm");
P.fA("What is the All Endpoints target?","targ_pkg-03.htm");
P.fA("What is a collection?","targ_pkg-04.htm");
P.fA("What is an excluded target?","targ_pkg-05.htm");
P.fA("What is a directly assigned target?","targ_pkg-06.htm");
P.fA("Viewing targets","targ_pkg-07.htm");
P.fA("Browsing targets","targ_pkg-08.htm");
P.fA("Viewing members of a target","targ_pkg-09.htm");
P.fA("Searching for targets","targ_pkg-10.htm");
P.fA("Viewing target details","targ_pkg-11.htm");
P.fA("Viewing packages assigned to a target","targ_pkg-12.htm");
P.fA("What is a package?","targ_pkg-13.htm");
P.fA("Viewing packages","targ_pkg-14.htm");
P.fA("Browsing packages","targ_pkg-15.htm");
P.fA("Searching for packages","targ_pkg-16.htm");
P.fA("Viewing targets that have been assigned a package","targ_pkg-17.htm");
P.fA("Viewing package details","targ_pkg-18.htm");
P.fA("Creating and editing policies","policies-01.htm");
P.fA("What is a policy?","policies-02.htm");
P.fA("General directions for creating and editing policies","policies-03.htm");
P.fA("Editing a policy for multiple packages (Edit All)","policies-04.htm");
P.fA("Previewing and saving policy changes","policies-05.htm");
P.fA("Notes about saving policies","policies-06.htm");
P.fA("Adding and removing packages from a policy","policies-07.htm");
P.fA("Adding packages to a policy","policies-08.htm");
P.fA("Removing packages from a policy","policies-09.htm");
P.fA("Specifying states and schedules for packages in a policy","policies-10.htm");
P.fA("Overview of installation states","policies-11.htm");
P.fA("Setting the primary and secondary states","policies-12.htm");
P.fA("Creating WoW deployments","policies-13.htm");
P.fA("Overview of schedules","policies-14.htm");
P.fA("Setting the primary and secondary schedule for packages","policies-15.htm");
P.fA("Setting the update schedule for packages","policies-16.htm");
P.fA("Setting the repair schedule for packages","policies-17.htm");
P.fA("Setting common schedules for multiple packages","policies-18.htm");
P.fA("Conflict resolution: states and schedules in policies","policies-19.htm");
P.fA("Resolving differences in package states or schedules","policies-20.htm");
P.fA("Setting the install priority for packages in a policy","policies-21.htm");
P.fA("What is install priority?","policies-22.htm");
P.fA("Conflict resolution: Packages with the same install priority","policies-23.htm");
P.fA("Conflict resolution: when multiple users edit the same policy ","policies-24.htm");
P.fA("Copying policies","policies-25.htm");
P.fA("Deleting policies","policies-26.htm");
P.fA("Managing software, data, and updates","policies-27.htm");
P.fA("Endpoint environment management concepts","policies-28.htm");
P.fA("Use cases","policies-29.htm");
P.fA("Editing policies from Package View","policies-30.htm");
P.fA("Setting a blackout period for a target","blackout-1.htm");
P.fA("What is a blackout period?","blackout-2.htm");
P.fA("Setting the blackout period for a target","blackout-3.htm");
P.fA("Exempting packages from the blackout period","blackout-4.htm");
P.fA("Specifying the Policy Service schedule for a target","sub_serv-1.htm");
P.fA("What is the Policy Service?","sub_serv-2.htm");
P.fA("Setting the schedule for Policy Service updates","sub_serv-3.htm");
P.fA("Specifying reboot settings for Windows targets","power_options-1.htm");
P.fA("Setting Power Options for Windows targets","power_options-2.htm");
P.fA("Setting tuner and package properties for a target","props-1.htm");
P.fA("Overview of tuner and package policies","props-2.htm");
P.fA("Setting tuner properties","props-3.htm");
P.fA("Setting package properties","props-4.htm");
P.fA("Tuner and package properties format","props-5.htm");
P.fA("Deleting tuner and package properties","props-6.htm");
P.fA("Conflict resolution: property values","props-7.htm");
P.fA("Conflict resolution: When multiple users edit properties","props-8.htm");
P.fA("Specifying transmitter permissions for a target","tx_login-1.htm");
P.fA("What are transmitter permissions?","tx_login-2.htm");
P.fA("Adding or editing transmitter permissions","tx_login-3.htm");
P.fA("Deleting transmitter permissions","tx_login-4.htm");
P.fA("Specifying the profile for a target","tx_login-5.htm");
P.fA("What is a profile?","tx_login-6.htm");
P.fA("Changing the profile for a target","tx_login-7.htm");
P.fA("Viewing policy compliance","pol_comp-01.htm");
P.fA("What is policy compliance?","pol_comp-02.htm");
P.fA("Definition of compliance","pol_comp-03.htm");
P.fA("BMC BladeLogic Client Automation BMC BladeLogic Client Automation Prerequisites for policy compliance","pol_comp-04.htm");
P.fA("Setting up the console server for policy compliance","pol_comp-05.htm");
P.fA("Setting up endpoints for policy compliance","pol_comp-06.htm");
P.fA("Viewing policy compliance for targets and packages","pol_comp-07.htm");
P.fA("Overall compliance queries and compliance reports","pol_comp-08.htm");
P.fA("Locating targets and running queries","pol_comp-09.htm");
P.fA("Compliance reports","pol_comp-10.htm");
P.fA("Integration with Patch Management","patch-01.htm");
P.fA("Prerequisites for integration with Patch Management","patch-02.htm");
P.fA("What is a patch group?","patch-03.htm");
P.fA("What is a patch group assignment state?","patch-04.htm");
P.fA("What is Patch Service?","patch-05.htm");
P.fA("Assigning patch groups to targets","patch-06.htm");
P.fA("Removing patch groups from a policy","patch-07.htm");
P.fA("Simulating the installation of patches","patch-08.htm");
P.fA("Viewing more details about the installation of patch groups","patch-09.htm");
P.fA("Overriding the Patch Service update schedule for target machines","patch-10.htm");
P.fA("Exempting Patch Service from the blackout period","patch-11.htm");
P.fA("Policy compliance for patch groups","patch-12.htm");
P.fA("Integrating with Deployment Manager","update_now-1.htm");
P.fA("Prerequisites for integration with Deployment Manager","update_now-2.htm");
P.fA("Enabling and disabling immediate policy updates","update_now-3.htm");
P.fA("Performing an immediate policy update","update_now-4.htm");
P.fA("Monitoring and viewing the status of a policy update","update_now-5.htm");
P.fA("Stopping and retrying policy updates","update_now-6.htm");
P.fA("How does the immediate policy update work?","update_now-7.htm");
P.fA("Blackout periods and immediate policy updates","update_now-8.htm");
P.fA("Edit Primary Schedule","z_schedule-1.htm");
P.fA("Edit Secondary Schedule","z_schedule-2.htm");
P.fA("Edit Update Schedule","z_schedule-3.htm");
P.fA("Edit Repair Schedule","z_schedule-4.htm");
P.fA("Set Common Schedule","z_schedule-5.htm");
P.fA("Package Details","z_details-1.htm");
P.fA("Target Details","z_details-2.htm");
P.fA("Target View","z_targ_vw-1.htm");
P.fA("Update Preview","z_targ_vw-2.htm");
P.fA("Status of Policy Update","z_targ_vw-3.htm");
P.fA("Blackout Period (Edit Policy)","z_target_set-1.htm");
P.fA("Tuner and Package Properties (Edit Policy &gt; Advanced)","z_target_set-2.htm");
P.fA("Transmitter Permissions (Edit Policy &gt; Advanced)","z_target_set-3.htm");
P.fA("Add\\Edit Transmitter Permissions","z_target_set-4.htm");
P.fA("Install Priority","z_target_set-5.htm");
P.fA("Policy Service Schedule (Edit Policy)","z_target_set-6.htm");
P.fA("Profile (Edit Policy &gt; Advanced)","z_target_set-7.htm");
P.fA("Power Options (Edit Policy)","z_target_set-8.htm");
P.fA("Choose Profile","z_target_set-9.htm");
P.fA("Package View","z_pkg_vw-1.htm");
P.fA("Packages (Edit Policy)","z_pol_asgn-1.htm");
P.fA("Preview Policy Changes","z_pol_asgn-2.htm");
P.fA("Delete Preview","z_pol_asgn-3.htm");
P.fA("Copy Policy","z_pol_asgn-4.htm");
P.fA("Edit Target List","z_ar_targ-1.htm");
P.fA("Edit Package List","z_ar_pkg-1.htm");
P.fA("Edit Package List (from Transmitter)","z_ar_pkg_tx-1.htm");
P.fA("Plug-in Configuration","z_pi_config-1.htm");
P.fA("Preview Plug-in Changes","z_pi_config-2.htm");
P.fA("Configuration","z_config-1.htm");
P.fA("Advanced Options","z_config-2.htm");
P.fA("Compliance Options","z_config-3.htm");
P.fA("Power Setting Profile Configuration","z_config-4.htm");
P.fA("Access Control","z_acl-1.htm");
P.fA("Access Control","z_acl-2.htm");
P.fA("Compliance: Target View","z_pc-1.htm");
P.fA("Compliance: Package View","z_pc-2.htm");
P.fA("Compliance Reports","z_pc-3.htm");
P.fA("Compliance Details","z_pc-4.htm");
P.fA("Export Query","z_pc-5.htm");
P.fA("Patch Groups (Edit Policy &gt; Patches)","z_patch-1.htm");
P.fA("Reboot Settings (Edit Policy &gt; Reboot Settings)","z_patch-2.htm");
P.fA("Patch Service Schedule (Edit Policy &gt; Patches)","z_patch-3.htm");
P.fA("Simulate Patch Installation (Edit Policy &gt; Patches)","z_patch-4.htm");
P.fA("Patch Simulation Logs (Edit Policy &gt; Patches)","z_patch-5.htm");
P.fA("Preview Policy Changes","z_patch-6.htm");
P.fA("Edit Patch Group List (Edit Policy &gt; Patches)","z_patch-7.htm");
}
